export enum Permission {
    /**
     * Create permissions
     */
    CREATE_USER = 'CREATE_USER',
    CREATE_PROBLEM = 'CREATE_PROBLEM',
    CREATE_CONTEST = 'CREATE_CONTEST',
    CREATE_GROUP = 'CREATE_GROUP',
    CREATE_SEASON = 'CREATE_SEASON',
    CREATE_TOPIC = 'CREATE_TOPIC',
    CREATE_TAG = 'CREATE_TAG',
    CREATE_SEASON_TOPIC = 'CREATE_SEASON_TOPIC',
    CREATE_SEASON_TOPIC_PROBLEM = 'CREATE_SEASON_TOPIC_PROBLEM',
    CREATE_SEASON_TOPIC_PROBLEM_USER = 'CREATE_SEASON_TOPIC_PROBLEM_USER',
    CREATE_USER_CONTEST = 'CREATE_USER_CONTEST',
    CREATE_USERPROFILE = 'CREATE_USERPROFILE',
    CREATE_USER_TOPIC = 'CREATE_USER_TOPIC',
    CREATE_USER_CONTEST_PROBLEM = 'CREATE_USER_CONTEST_PROBLEM',

    /**
     * Manage permissions
     */
    MANAGE_USER = 'MANAGE_USER',
    MANAGE_PROBLEM = 'MANAGE_PROBLEM',
    MANAGE_CONTEST = 'MANAGE_CONTEST',
    MANAGE_GROUP = 'MANAGE_GROUP',
    MANAGE_SEASON = 'MANAGE_SEASON',
    MANAGE_TOPIC = 'MANAGE_TOPIC',
    MANAGE_TAG = 'MANAGE_TAG',
    MANAGE_SEASON_TOPIC = 'MANAGE_SEASON_TOPIC',
    MANAGE_SEASON_TOPIC_PROBLEM = 'MANAGE_SEASON_TOPIC_PROBLEM',
    MANAGE_SEASON_TOPIC_PROBLEM_USER = 'MANAGE_SEASON_TOPIC_PROBLEM_USER',
    MANAGE_USER_CONTEST = 'MANAGE_USER_CONTEST',
    MANAGE_USERPROFILE = 'MANAGE_USERPROFILE',
    MANAGE_USER_TOPIC = 'MANAGE_USER_TOPIC',
    MANAGE_USER_CONTEST_PROBLEM = 'MANAGE_USER_CONTEST_PROBLEM',

    /**
     * Update permissions
     */
    UPDATE_USER = 'UPDATE_USER',
    UPDATE_PROBLEM = 'UPDATE_PROBLEM',
    UPDATE_CONTEST = 'UPDATE_CONTEST',
    UPDATE_GROUP = 'UPDATE_GROUP',
    UPDATE_SEASON = 'UPDATE_SEASON',
    UPDATE_TOPIC = 'UPDATE_TOPIC',
    UPDATE_TAG = 'UPDATE_TAG',
    UPDATE_SEASON_TOPIC = 'UPDATE_SEASON_TOPIC',
    UPDATE_SEASON_TOPIC_PROBLEM = 'UPDATE_SEASON_TOPIC_PROBLEM',
    UPDATE_SEASON_TOPIC_PROBLEM_USER = 'UPDATE_SEASON_TOPIC_PROBLEM_USER',
    UPDATE_USER_CONTEST = 'UPDATE_USER_CONTEST',
    UPDATE_USERPROFILE = 'UPDATE_USERPROFILE',
    UPDATE_USER_TOPIC = 'UPDATE_USER_TOPIC',
    UPDATE_USER_CONTEST_PROBLEM = 'UPDATE_USER_CONTEST_PROBLEM',

    /**
     * Read permissions
     */
    READ_USER = 'READ_USER',
    READ_PROBLEM = 'READ_PROBLEM',
    READ_CONTEST = 'READ_CONTEST',
    READ_GROUP = 'READ_GROUP',
    READ_SEASON = 'READ_SEASON',
    READ_TOPIC = 'READ_TOPIC',
    READ_TAG = 'READ_TAG',
    READ_SEASON_TOPIC = 'READ_SEASON_TOPIC',
    READ_SEASON_TOPIC_PROBLEM = 'READ_SEASON_TOPIC_PROBLEM',
    READ_SEASON_TOPIC_PROBLEM_USER = 'READ_SEASON_TOPIC_PROBLEM_USER',
    READ_USER_CONTEST = 'READ_USER_CONTEST',
    READ_USERPROFILE = 'READ_USERPROFILE',
    READ_USER_TOPIC = 'READ_USER_TOPIC',
    READ_USER_CONTEST_PROBLEM = 'READ_USER_CONTEST_PROBLEM',

    /**
     * Delete permissions
     */
    DELETE_USER = 'DELETE_USER',
    DELETE_PROBLEM = 'DELETE_PROBLEM',
    DELETE_CONTEST = 'DELETE_CONTEST',
    DELETE_GROUP = 'DELETE_GROUP',
    DELETE_SEASON = 'DELETE_SEASON',
    DELETE_TOPIC = 'DELETE_TOPIC',
    DELETE_TAG = 'DELETE_TAG',
    DELETE_SEASON_TOPIC = 'DELETE_SEASON_TOPIC',
    DELETE_SEASON_TOPIC_PROBLEM = 'DELETE_SEASON_TOPIC_PROBLEM',
    DELETE_SEASON_TOPIC_PROBLEM_USER = 'DELETE_SEASON_TOPIC_PROBLEM_USER',
    DELETE_USER_CONTEST = 'DELETE_USER_CONTEST',
    DELETE_USERPROFILE = 'DELETE_USERPROFILE',
    DELETE_USER_TOPIC = 'DELETE_USER_TOPIC',
    DELETE_USER_CONTEST_PROBLEM = 'DELETE_USER_CONTEST_PROBLEM'
}